// Builds js/icons-data.js from Bootstrap Icons (MIT), keeping only the icons CaseVault uses.
//   npm pack bootstrap-icons && tar xzf bootstrap-icons-*.tgz
//   node scripts/make-icons.js path/to/package/icons
// Add a name to NAMES and run it again to use another icon (browse https://icons.getbootstrap.com).
'use strict';
const fs = require('fs');
const path = require('path');

const NAMES = `
shield-lock-fill shield-check shield-fill-check shield-fill-exclamation safe2 gear sliders
folder folder-fill folder2-open plus-lg plus-circle search funnel eye eye-slash eye-slash-fill
layout-sidebar layout-sidebar-inset info-circle journal-text journal-bookmark clock-history
files envelope envelope-at pencil-square pencil clipboard2-check clipboard2-pulse person-vcard
person-badge person-circle people archive trash3 x-lg x-circle check-circle-fill check2 check2-all
exclamation-triangle-fill exclamation-circle arrow-counterclockwise lock-fill unlock hourglass-split
download upload printer copy calculator calculator-fill capsule-pill cone-striped diagram-3-fill
geo-alt geo journal-medical file-earmark-pdf-fill file-earmark-word-fill file-earmark-text
file-earmark-image file-earmark-music file-earmark-play file-earmark-spreadsheet file-earmark
file-earmark-zip moon-stars-fill sun-fill circle-half cpu wifi-off globe2 hdd hdd-fill usb-drive
key envelope-paper list-check activity save arrow-repeat box-arrow-up-right chevron-right
chevron-down house-door speedometer2 book bookmark-star stars magic lightning-charge
calendar-event calendar-check flag card-checklist hash box-seam car-front map mic telephone
send paperclip question-circle lightbulb three-dots tools database fingerprint graph-up-arrow
table bar-chart-line-fill cash-coin file-earmark-ruled clipboard2-data signpost-split
box-arrow-left plug arrow-left-right collection bank2 building
camera-video inbox type-bold type-italic type-underline type-h2 list-ul list-ol grip-vertical currency-bitcoin
image person-lines-fill robot chat-left-text bookshelf link-45deg pin-angle eye-fill plus-square pencil-fill
quote hr file-earmark-plus arrow-up arrow-down chevron-up
`.trim().split(/\s+/);

const dir = process.argv[2];
if (!dir) { console.error('usage: node scripts/make-icons.js <bootstrap-icons/icons>'); process.exit(1); }
const out = {};
for (const name of [...new Set(NAMES)].sort()) {
  const svg = fs.readFileSync(path.join(dir, `${name}.svg`), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  // Each child as [tag, {attr: value}]; icons are paths, circles and rects only.
  const els = [];
  for (const m of inner.matchAll(/<(path|circle|rect|ellipse)\b([^>]*?)\/?>/g)) {
    const attrs = {};
    for (const a of m[2].matchAll(/([a-z-]+)="([^"]*)"/g)) attrs[a[1]] = a[2];
    els.push([m[1], attrs]);
  }
  if (!els.length) throw new Error(`${name}: nothing to draw`);
  out[name] = els;
}
const version = JSON.parse(fs.readFileSync(path.join(dir, '..', 'package.json'), 'utf8')).version;
fs.writeFileSync(path.join(__dirname, '..', 'js', 'icons-data.js'),
  `/* Bootstrap Icons ${version} (MIT, icons.getbootstrap.com), only the icons CaseVault uses.
 * Generated by scripts/make-icons.js; don't edit by hand. License: vendor/bootstrap-icons/LICENSE */
'use strict';
(function (root) {
  const ICONS = ${JSON.stringify(out)};
  if (typeof module !== 'undefined' && module.exports) module.exports = ICONS;
  else root.CVIconData = ICONS;
})(this);
`);
console.log(`${Object.keys(out).length} icons written to js/icons-data.js`);
